###### Cargar paquetes de R ###################
library(shiny)
library(foreign)
library(ggplot2)
library(nortest)
library(dplyr)
library(rms)
library(ggthemr)
library(ggfortify)
library(shinysky)
library(openintro)
library(plotrix)
library(effects)
library(plotROC)
library(xtable)
library(data.table)
library(pROC)
library(epiR)
library(DT)
library(shinythemes)

